/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        mws: {
          white: 'var(--mws-white)',
          black: 'var(--mws-black)',
          'gray-50': 'var(--mws-gray-50)',
          'gray-60': 'var(--mws-gray-60)',
          'gray-75': 'var(--mws-gray-75)',
          'gray-100': 'var(--mws-gray-100)',
          'gray-150': 'var(--mws-gray-150)',
          'gray-200': 'var(--mws-gray-200)',
          'gray-250': 'var(--mws-gray-250)',
          'gray-300': 'var(--mws-gray-300)',
          'gray-325': 'var(--mws-gray-325)',
          'gray-350': 'var(--mws-gray-350)',
          'gray-400': 'var(--mws-gray-400)',
          'gray-450': 'var(--mws-gray-450)',
          'gray-475': 'var(--mws-gray-475)',
          'gray-500': 'var(--mws-gray-500)',
          'gray-550': 'var(--mws-gray-550)',
          'gray-600': 'var(--mws-gray-600)',
          'gray-650': 'var(--mws-gray-650)',
          'ink-500': 'var(--mws-ink-500)',
          'ink-600': 'var(--mws-ink-600)',
          'ink-650': 'var(--mws-ink-650)',
          'ink-800': 'var(--mws-ink-800)',
          'ink-700': 'var(--mws-ink-700)',
          'ink-900': 'var(--mws-ink-900)',
          'blue-700': 'var(--mws-blue-700)',
          'blue-600': 'var(--mws-blue-600)',
          'blue-550': 'var(--mws-blue-550)',
          'blue-500': 'var(--mws-blue-500)',
          'blue-400': 'var(--mws-blue-400)',
          'blue-100': 'var(--mws-blue-100)',
          'red-500': 'var(--mws-red-500)',
          'alpha-blue-15': 'var(--mws-alpha-blue-15)',
          'alpha-blue-50': 'var(--mws-alpha-blue-50)',
          'alpha-primary-10': 'var(--mws-alpha-primary-10)',
          'alpha-primary-15': 'var(--mws-alpha-primary-15)',
          'alpha-primary-20': 'var(--mws-alpha-primary-20)',
          'alpha-primary-25': 'var(--mws-alpha-primary-25)',
          'alpha-red-10': 'var(--mws-alpha-red-10)',
        },
      },
      fontFamily: {
        pretendard: ['Pretendard', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
