// This file is auto-generated by scripts/generate-images.mjs.
// Do not edit this file manually.

import img_btn_button_icon_default from '@/assets/images/btn/button-icon-default.svg'
import img_btn_button_icon_disabled from '@/assets/images/btn/button-icon-disabled.svg'
import img_btn_button_icon_hover from '@/assets/images/btn/button-icon-hover.svg'
import img_empty_empty_state from '@/assets/images/empty/empty-state.svg'
import img_input_calendar_active from '@/assets/images/input/calendar-active.svg'
import img_input_calendar_disabled from '@/assets/images/input/calendar-disabled.svg'
import img_input_calendar from '@/assets/images/input/calendar.svg'
import img_input_checkbox_active from '@/assets/images/input/checkbox-active.svg'
import img_input_checkbox_disabled from '@/assets/images/input/checkbox-disabled.svg'
import img_input_chevron_active from '@/assets/images/input/chevron-active.svg'
import img_input_chevron from '@/assets/images/input/chevron.svg'
import img_input_date_nav_next from '@/assets/images/input/date-nav-next.svg'
import img_input_date_nav_prev from '@/assets/images/input/date-nav-prev.svg'

export const icons = {
  "btn": {
    "buttonIconDefault": img_btn_button_icon_default,
    "buttonIconDisabled": img_btn_button_icon_disabled,
    "buttonIconHover": img_btn_button_icon_hover,
  },
  "empty": {
    "emptyState": img_empty_empty_state,
  },
  "input": {
    "calendarActive": img_input_calendar_active,
    "calendarDisabled": img_input_calendar_disabled,
    "calendar": img_input_calendar,
    "checkboxActive": img_input_checkbox_active,
    "checkboxDisabled": img_input_checkbox_disabled,
    "chevronActive": img_input_chevron_active,
    "chevron": img_input_chevron,
    "dateNavNext": img_input_date_nav_next,
    "dateNavPrev": img_input_date_nav_prev,
  },
} as const

export type IconGroups = typeof icons
export type IconGroup = keyof IconGroups
export type IconName<G extends IconGroup> = keyof IconGroups[G]
